Assign4
aarushi121/node-training pull request #4
Opened 2017-07-11 13:06 UTC by aarushi121

2017-07-11 16:43 UTC, rockon1985 requested changes
Make code styling changes.

2017-07-11 16:43 UTC, ketanTechracers commented on Assignment4/Assignment4.js
> +function ReadAppendWrite (read_file, append_file, write_file) {
- variable or parameter names must be _camelCased_ , not _underscore_separated_
- function name not correctly _camelCased_

2017-07-11 16:43 UTC, ketanTechracers commented on Assignment4/Assignment4.js
> +        console.log("-----------------------------------------------");
correct indentation here

2017-07-11 16:43 UTC, ketanTechracers commented on Assignment4/Assignment4.js
> +ReadAppendWrite("file1.txt", "file2.txt", "file3.txt");
add new line at the end of each file

2017-07-11 16:43 UTC, ketanTechracers commented on Assignment4/Assignment4.js
> +var fs = require('fs');
use `const` instead of `var`

2017-07-11 16:43 UTC, ketanTechracers commented on Assignment4/Assignment4.js
> +      if (err2)  throw err2;
two spaces between if() and throw clause. One space required. Correct rest of the places as well

2017-07-12 09:01 UTC, rockon1985 approved these changes
Good Job! Approved from my end!

2017-07-12 09:27 UTC, sakodiya requested changes

2017-07-12 09:27 UTC, sakodiya commented on Assignment4/Assignment4.js
> +          if (err2) throw err2;
@aarushi121 Please make separate function for throwing an error & writing console messages.

2017-07-12 09:45 UTC, devanshutechracers requested changes
Check the Spacing/Naming Convention and a Typo Error. I have made the comments.

2017-07-12 09:45 UTC, devanshutechracers commented on Assignment4/Assignment4.js
> +function readAppendWrite (readFile, appendFile, writeFile) {
`readAppendWrite (readFile, appendFile, writeFile)` should be `readAppendWrite(readFile, appendFile, writeFile)`.
Problem Type: Spacing

2017-07-12 09:45 UTC, devanshutechracers commented on Assignment4/Assignment4.js
> +  fs.readFile (readFile, function (err1, data1) {
`fs.readFile (readFile, function (err1, data1)` should be `fs.readFile(readFile, function (err1, data1)`.
Problem Type: Spacing

2017-07-12 09:45 UTC, devanshutechracers commented on Assignment4/Assignment4.js
> +  fs.readFile (readFile, function (err1, data1) {
`err1` and `data1`  can be a bit descritive, like `errorOnFile1Read`, `dataFromFile1` and similarly for other error and data parameter.
Problem Type: Naming Convention

2017-07-12 09:45 UTC, devanshutechracers commented on Assignment4/Assignment4.js
> +          if (err2) throw err2;
Throwing err2 on raising err3 error. Any logic behind this, which we should know?
Problem Type: Typo Error

2017-07-12 10:05 UTC, sakodiya commented on Assignment4/Assignment4.js
> +function checkError(error){
@aarushi121 We can make only function for error-throwing & printing console messages. Think about it.

2017-07-12 10:08 UTC, devanshutechracers requested changes
Spaces and Semicolon Syntax to improve

2017-07-12 10:08 UTC, devanshutechracers commented on Assignment4/Assignment4.js
> +function checkError(error){
space before starting block is missing.
Problem Type: Spacing

2017-07-12 10:08 UTC, devanshutechracers commented on Assignment4/Assignment4.js
> +{
Block to be started in same line as function declaration.
Problem Type: Linting

2017-07-12 10:08 UTC, devanshutechracers commented on Assignment4/Assignment4.js
> +  if(error)
space after `if` statement.
Problem Type: Spacing

2017-07-12 10:08 UTC, devanshutechracers commented on Assignment4/Assignment4.js
> +  fs.readFile (readFile, function (errorOnFile1Read, dataFromFile1) {
No Space after function calling and before its argument. This should be like `fs.readFile(read......`
Problem Type: Spacing

2017-07-12 10:08 UTC, devanshutechracers commented on Assignment4/Assignment4.js
> +    checkError (errorOnFile1Read);
Same here.
Problem Type: Spacing

2017-07-12 10:08 UTC, devanshutechracers commented on Assignment4/Assignment4.js
> +    print(dataFromFile1.toString())
Semicolon when line ends.
Problem Type: Missing Semicolon

2017-07-12 10:08 UTC, devanshutechracers commented on Assignment4/Assignment4.js
> +          checkError(errorOnFile3Write)
Semicolon when line ends.
Problem Type: Missing Semicolon

2017-07-12 11:58 UTC, sakodiya approved these changes

2017-07-13 09:34 UTC, devanshutechracers requested changes
Fix Space after if

2017-07-13 09:34 UTC, devanshutechracers commented on Assignment4/Assignment4.js
> +  if(error) {
space after `if` statement.
Problem Type: Spacing
Example:
`if (error) {` and not `if(error) {`

2017-07-19 13:16 UTC, devanshutechracers requested changes
Run Time Errors Observed while Test Run.

2017-07-19 13:16 UTC, devanshutechracers commented on Assignment4/Assignment4.js
> +        fs.writeFile(writeFile, datafromFile2, function (errorOnFile3Write) {
`datafromFile2` is not defined.

Read the detail of the error below.

-----
fs.writeFile(writeFile, datafromFile2, function (errorOnFile3Write) {

ReferenceError: datafromFile2 is not defined
    at /home/rails/work/training/aarushi_goyal/node-training/Assignment4/Assignment4.js:26:33
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)

-----

2017-07-19 13:16 UTC, devanshutechracers commented on Assignment4/Assignment4.js
> +          print(data2.toString());
`data2` is not defined.

Read the detail of the error below.

------
print(data2.toString());

ReferenceError: data2 is not defined
    at /home/rails/work/training/aarushi_goyal/node-training/Assignment4/Assignment4.js:28:17
    at FSReqWrap.oncomplete (fs.js:123:15)

------

2017-07-20 10:26 UTC, devanshutechracers approved these changes
Approved.

2017-07-20 10:26 UTC, merged